version: "3.8"

services:
  traffic_capture:
    image: traffic-capture-image
    container_name: traffic-capture
    build: ./traffic_capture
    networks:
      endpoint_net1:
      endpoint_net2:
      router_net1:
      router_net2:
      router_net3:
    privileged: true

  router1:
    image: router-image
    container_name: router-1
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - endpoint_net1
      - router_net1

  router2:
    image: router-image
    container_name: router-2
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - router_net1
      - router_net2

  router3:
    image: router-image
    container_name: router-3
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - router_net1
      - endpoint_net2
  
  router4:
    image: router-image
    container_name: router-4
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - router_net2
      - router_net3

  endpoint1:
    image: endpoint-image
    container_name: endpoint-1
    build: ./endpoint
    environment:
      - PORT=${PORT}
      - DATA_PATH=${DATA_PATH}
      - SOURCE_ID=${SOURCE_ID1}
      - DEST_ID=${DEST_ID1}
      - ROLE=${ROLE1}
    stdin_open: true
    tty: true
    depends_on:
      - router1
      - router2
      - router3
      - router4
      - endpoint2
    networks:
      - endpoint_net1

  endpoint2:
    image: endpoint-image
    container_name: endpoint-2
    build: ./endpoint
    environment:
      - PORT=${PORT}
      - DATA_PATH=${DATA_PATH}
      - ROLE=${ROLE2}
    stdin_open: true
    tty: true
    depends_on:
      - router1
      - router2
      - router3
      - router4
    networks:
      - endpoint_net2

networks:
  endpoint_net1:
    ipam:
      driver: default
      config:
        - subnet: 124.10.0.0/16
  endpoint_net2:
    ipam:
      driver: default
      config:
        - subnet: 124.20.0.0/16
  router_net1:
    ipam:
      driver: default
      config:
        - subnet: 10.21.0.0/16
  router_net2:
    ipam:
      driver: default
      config:
        - subnet: 10.22.0.0/16
  router_net3:
    ipam:
      driver: default
      config:
        - subnet: 10.23.0.0/16