version: "3.8"

services:
  router1:
    image: router-image
    container_name: router-1
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - client_net1
      - router_net1

  router2:
    image: router-image
    container_name: router-2
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - router_net1
      - router_net2

  router3:
    image: router-image
    container_name: router-3
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - router_net1
      - client_net2
  
  router4:
    image: router-image
    container_name: router-4
    build: ./router
    stdin_open: true
    tty: true
    networks:
      - router_net2
      - router_net3

  client1:
    image: client-image
    container_name: client-1
    build: ./client
    environment:
      - PORT=${PORT}
      - DATA_PATH=${DATA_PATH}
      - CAN_STREAM=${CAN_STREAM1}
      - CONTAINER_NAME=client-1
    stdin_open: true
    tty: true
    depends_on:
      - router1
    networks:
      - client_net1

  client2:
    image: client-image
    container_name: client-2
    build: ./client
    environment:
      - PORT=${PORT}
      - DATA_PATH=${DATA_PATH}
      - CAN_STREAM=${CAN_STREAM2}
      - CONTAINER_NAME=client-2
    stdin_open: true
    tty: true
    depends_on:
      - router3
    networks:
      - client_net2

networks:
  client_net1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  client_net2:
    ipam:
      driver: default
      config:
        - subnet: 172.168.0.0/24
  router_net1:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
  router_net2:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
  router_net3:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24